# Generated by Django 2.2.15 on 2020-09-23 04:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='child_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/child/%Y/%m/%d'),
        ),
    ]
