# Generated by Django 2.2.15 on 2020-09-10 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
        migrations.AddField(
            model_name='customuser',
            name='child_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='child_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image/child'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='child_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='image/family')),
                ('gender', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
