# Generated by Django 2.2.15 on 2020-09-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('back_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('family_ability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Substory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(upload_to='')),
                ('next_id', models.IntegerField(blank=True, null=True)),
                ('has_branch', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.Substory')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(upload_to='')),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='stories.Substory')),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stories.Branch')),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stories.Substory')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='stories.Character')),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='stories.Substory')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stories.Story'),
        ),
    ]
