# Generated by Django 2.2.15 on 2020-09-24 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('back_image', models.ImageField(upload_to='')),
                ('story_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('family_ability', models.BooleanField()),
                ('gender', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Substory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('next_id', models.IntegerField(blank=True, null=True)),
                ('has_branch', models.BooleanField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substories', to='stories.Story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.Substory')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='substory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_story', to='stories.Substory'),
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stories.Branch')),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selects', to='stories.Substory')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='stories.Character')),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='stories.Substory')),
            ],
        ),
        migrations.CreateModel(
            name='MySubstory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_id', models.IntegerField(blank=True, null=True)),
                ('is_end', models.BooleanField()),
                ('substory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Substory')),
            ],
        ),
        migrations.CreateModel(
            name='MyStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('story_name', models.CharField(max_length=30)),
                ('mystory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substories', to='stories.MySubstory')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystories', to='stories.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycharacters', to='stories.Character')),
                ('family', models.ManyToManyField(related_name='mycharacters', to='accounts.Family')),
                ('mystory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycharacters', to='stories.MyStory')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='stories.Story'),
        ),
    ]
