# Generated by Django 2.2.15 on 2020-09-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='substory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_story', to='stories.Substory'),
        ),
    ]
