# Generated by Django 2.2.15 on 2020-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200924_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='left_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='right_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
