# Generated by Django 2.2.15 on 2020-09-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200920_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystory',
            name='mystory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substories', to='stories.MySubstory'),
        ),
    ]
