# Generated by Django 2.2.15 on 2020-09-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200924_1838'),
        ('stories', '0002_auto_20200924_1540'),
    ]

    operations = [
    ]
