# Generated by Django 2.2.15 on 2020-09-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200920_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='substory',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='substories', to='stories.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='substory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_story', to='stories.Substory'),
        ),
    ]
