# Generated by Django 2.2.15 on 2020-09-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_merge_20200924_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyimage',
            old_name='tag',
            new_name='path',
        ),
        migrations.AddField(
            model_name='mystory',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyimage',
            name='is_main_character',
            field=models.BooleanField(default=False),
        ),
    ]
