# Generated by Django 2.2.15 on 2020-09-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200923_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substory',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substories', to='stories.Story'),
        ),
    ]
