# Generated by Django 2.2.15 on 2020-09-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200927_2105'),
        ('stories', '0005_mystory_finished'),
    ]

    operations = [
    ]
