# Generated by Django 2.2.15 on 2020-09-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_merge_20200927_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryImage',
        ),
    ]
