# Generated by Django 2.2.15 on 2020-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
